gin:
  host: 127.0.0.1
  port: 40020
  mode: debug

mysql:
  host: 127.0.0.1
  port: 53306
  dbname: demo
  # 数据库登录用户
  username: root
  # 数据库密码
  password: root123456
  # 数据库名字
  timeout: 10s
  maxConn: 200
  maxOpen: 200

postgresql:
  host: 127.0.0.1
  port: 55433
  dbname: demo
  # 数据库登录用户
  username: huang
  # 数据库密码
  password: root123456

redis:
  host: 127.0.0.1
  port: 56379
  password:
  DB: 0

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: admin
  password: root123456
  vhost: local

grpc:
  host: 127.0.0.1
  port: 50051

logger:
  console:
    enable: true
    level: info
  file:
    enable: true
    level: info
    path: logs/gin_app.log
    maxSize: 300 # 日志文件大小
    maxBackupCount: 10 # 日志文件数
  external:
    enable: false
    level: info
    service: "elk" # 日志外部服务类型：elk, logstash, etc.
    url: "http://localhost:9200"
    index: "gin-logs" # ELK索引
